# Generated by Django 5.1.6 on 2025-02-17 00:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_post_o0lbny', max_length=255, null=True, verbose_name='image'),
        ),
    ]
